// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsLS7_U2YEjCI21X59b_Hepi3MgQ-Xek',
    appId: '1:1062985917339:web:d7327767df2c2bcd90773e',
    messagingSenderId: '1062985917339',
    projectId: 'bookwise-2a19e',
    authDomain: 'bookwise-2a19e.firebaseapp.com',
    storageBucket: 'bookwise-2a19e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXFOisPGPKtbxInX7697eFFRJz0qKPGY',
    appId: '1:1062985917339:android:235a73f9fffc5b1c90773e',
    messagingSenderId: '1062985917339',
    projectId: 'bookwise-2a19e',
    storageBucket: 'bookwise-2a19e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31N8pRC17YmhOc3I_sgBtmCrthW6dthY',
    appId: '1:1062985917339:ios:053078397a697eaf90773e',
    messagingSenderId: '1062985917339',
    projectId: 'bookwise-2a19e',
    storageBucket: 'bookwise-2a19e.firebasestorage.app',
    iosBundleId: 'com.example.app1Paralelos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31N8pRC17YmhOc3I_sgBtmCrthW6dthY',
    appId: '1:1062985917339:ios:053078397a697eaf90773e',
    messagingSenderId: '1062985917339',
    projectId: 'bookwise-2a19e',
    storageBucket: 'bookwise-2a19e.firebasestorage.app',
    iosBundleId: 'com.example.app1Paralelos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGsLS7_U2YEjCI21X59b_Hepi3MgQ-Xek',
    appId: '1:1062985917339:web:5f689ac8f9abc54490773e',
    messagingSenderId: '1062985917339',
    projectId: 'bookwise-2a19e',
    authDomain: 'bookwise-2a19e.firebaseapp.com',
    storageBucket: 'bookwise-2a19e.firebasestorage.app',
  );
}
